# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zU8nvvSz7Yd9sXfx5i8VTdEJZFNfDe9s
"""



# Simple Input/Output Program

# Taking inputs
int_input = int(input("Enter an integer: "))
float_input = float(input("Enter a float: "))
string_input = input("Enter a string: ")

# Showing outputs
print("You entered the integer:", int_input)
print("You entered the float:", float_input)
print("You entered the string:", string_input)
