# -*- coding: utf-8 -*-
"""intership day 2 task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WnQBYb9LC0g9UI3ylOP16zOjmPyVD1cJ
"""



# Task: String Slicing & Simple Calculator

# String Slicing
full_name = input("Enter your full name (first + last): ")
space_index = full_name.find(" ")
first_name = full_name[:space_index]
last_name = full_name[space_index+1:]
print("First Name:", first_name)
print("Last Name:", last_name)

# Calculator
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
add = num1 + num2
sub = num1 - num2
mul = num1 * num2
div = num1 / num2
print(f"Addition: {add}")
print(f"Subtraction: {sub}")
print(f"Multiplication: {mul}")
print(f"Division: {div}")