# -*- coding: utf-8 -*-
"""intership task day 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jdigzh11qexpawtrUraBev6qGFNkfF5Q
"""



def is_valid_email(email):
    return "@" in email and "." in email

def get_contact_name():
    return input("Enter contact name: ").strip().title()

def add_contact(contacts):
    name = get_contact_name()
    if name in contacts:
        print("Contact already exists.")
        return
    phone = input("Enter phone number: ").strip()
    email = input("Enter email address: ").strip()
    if not is_valid_email(email):
        print("Invalid email format.")
        return
    contacts[name] = {"phone": phone, "email": email}
    print(f"{name} added successfully.")

def update_contact(contacts):
    name = get_contact_name()
    if name not in contacts:
        print("Contact not found.")
        return
    phone = input("Enter new phone number: ").strip()
    email = input("Enter new email address: ").strip()
    if not is_valid_email(email):
        print("Invalid email format.")
        return
    contacts[name] = {"phone": phone, "email": email}
    print(f"{name}'s contact updated.")

def retrieve_contact(contacts):
    name = get_contact_name()
    if name in contacts:
        print(f"Name: {name}")
        print(f"Phone: {contacts[name]['phone']}")
        print(f"Email: {contacts[name]['email']}")
    else:
        print("Contact not found.")

def view_all_contacts(contacts):
    if not contacts:
        print("No contacts to show.")
        return
    for name, info in contacts.items():
        print(f"{name}: Phone: {info['phone']}, Email: {info['email']}")

def contact_book():
    contacts = {}
    while True:
        print("\n--- Contact Book ---")
        print("1. Add Contact")
        print("2. Update Contact")
        print("3. Retrieve Contact")
        print("4. View All Contacts")
        print("5. Exit")
        choice = input("Select an option: ").strip()
        if choice == "1":
            add_contact(contacts)
        elif choice == "2":
            update_contact(contacts)
        elif choice == "3":
            retrieve_contact(contacts)
        elif choice == "4":
            view_all_contacts(contacts)
        elif choice == "5":
            break
        else:
            print("Invalid option. Try again.")

contact_book()
7