# -*- coding: utf-8 -*-
"""day 3 task 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DrxnjVDoVjetv8Z50sqGMB5eyAGXApih
"""



sentence = input("Enter a sentence: ")
words_list = sentence.split()
print(words_list)
joined_sentence = " - ".join(words_list)
print(joined_sentence)
name_tuple = ("Zubia", "Tanoli")
print(name_tuple[0])
print(name_tuple[1])

sentence = input("Enter a sentence: ")
words_list = sentence.split()
print(words_list)
joined_sentence = " - ".join(words_list)
print(joined_sentence)
name_tuple = ("Zubia", "Tanoli")
print(name_tuple[0])
print(name_tuple[1])
